environment:
   LANG: en_US.utf-8
   APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
   APPVEYOR_SSH_BLOCK: true

services:
  - postgresql

init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: lsb_release -d
 - sh: ip -o -4 a
 - sh: |
     sudo apt-get -yqq install virt-what &&
     sudo virt-what
 - sh: export LANG=en_US.utf8
 
test_script:
  - sh: cat $__APPVEYOR_DIR/env | grep JAVA_TOOL_OPTIONS || true
  - sh: |
      unset JAVA_TOOL_OPTIONS
      sed -i -e '/ JAVA_TOOL_OPTIONS=/d' $__APPVEYOR_DIR/env
      sed -i -e '/ JAVA_TOOL_OPTIONS=/d' $HOME/.profile
      cat $__APPVEYOR_DIR/env | grep JAVA_TOOL_OPTIONS || true
  - sh: env|grep JAVA_TOOL_OPTIONS || true
  - sh: env
  - sh: cat ${HOME}/.profile
  - sh: locale
  - sh: locale -a
  - sh: export PGUSER=postgres
  - sh: export PGPASSWORD=Password12!
  - sh: echo $PWD $USER $PGUSER $PGPASSWORD
  - sh: createdb test_db_setup
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


build: off

