environment:
   LANG: en_US.utf-8
   APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUvrULRVnqephhFVqt2Gm+MRkLewIa7bfrrHTp1+Y6ulBlycVumHKsLMzeulCnxUP7+gVJ9cIQtbNBOt9oGEcSGBNGtmoDPsNOo6lA/9eVkQQR+WlgKYFK2LgtJY2FMpmkeD8BA06lz0arR6oQAac6Yjfn7HQq0XRkmJaFwrgc258JwSldbp9RNGDd7j6DzF1F3QsiLRFeHqZni6eNMnC3Xhmh0Jj4hDjYpeXWKuZjGPXAuVry0XTXPoLaUNfi0R9aDhtD8NszdzWKNwYt2iPKBVaSkMeDFkyLo3+CGLHKw//Uw8GIhtRQk4S6/Yfo7LS3leOJxJs7dryJiUS0IwT9 wasapl@appveyor.com
#   APPVEYOR_SSH_BLOCK: true
#   APPVEYOR_VNC_BLOCK: true

init:

 - sh: echo $PATH| tr ":" '\n'
 - sh: cat $HOME/.profile
 - sh: cat /etc/profile
 - sh: ps auxe | tr ":" '\n' || true
 - appveyor version
 - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: pwd
 - sh: |
     if [ $(uname -s) = "Darwin" ]; then
         IS_MAC=true
     else
         IS_MAC=false
     fi
 - sh: |
     if grep -Eq '/(lxc|docker)/[[:xdigit:]]{64}' /proc/1/cgroup; then
         IS_DOCKER=true
     else
         IS_DOCKER=false
     fi
 - sh: if $IS_MAC; then sw_vers  ; fi
 - sh: if $IS_MAC; then ls -la /usr/local/var/appveyor/build-agent/ || true; fi
 - sh: if $IS_MAC; then cat /usr/local/var/appveyor/build-agent/psw || true; fi
 - sh: if ! $IS_DOCKER && ! $IS_MAC; then lsb_release -d; fi
 - sh: if ! $IS_DOCKER && ! $IS_MAC; then ip -o -4 a; fi
 - sh: |
     if ! $IS_DOCKER  && ! $IS_MAC; then
       sudo apt-get -yqq install virt-what &&
       sudo virt-what
     fi
 - sh: |
     if ! $IS_MAC; then
       sudo apt-get -y update
       #sudo apt-get -y install apache2 apache2-dev
     fi
     
#install:
# - sh: sudo apt-get -y install language-pack-en language-pack-ru
# - sh: |
#     sudo chmod -x /etc/update-motd.d/*
#     echo '#!/bin/sh
#     [ -r /etc/os-release ] && . /etc/os-release
#     printf "Appveyor Worker\n"
#     printf "OS %s (%s %s %s)\n" "$PRETTY_NAME" "$(uname -o)" "$(uname -r)" "$(uname -m)"
#     ' | sudo tee /etc/update-motd.d/00-appveyor
#     sudo chmod +x /etc/update-motd.d/00-appveyor

test_script:
  - sh: echo $FOO
  - sh: cat $__APPVEYOR_DIR/env | grep JAVA_TOOL_OPTIONS || true
  - sh: |
      unset JAVA_TOOL_OPTIONS
      sed -i -e '/ JAVA_TOOL_OPTIONS=/d' $__APPVEYOR_DIR/env
      sed -i -e '/ JAVA_TOOL_OPTIONS=/d' $HOME/.profile
      cat $__APPVEYOR_DIR/env | grep JAVA_TOOL_OPTIONS || true
  - sh: env|grep JAVA_TOOL_OPTIONS || true
#   - sh: env
  - sh: cat ${HOME}/.profile
#   - sh: locale
#   - sh: locale -a
  - sh: |
      if $IS_MAC; then
        bash -ex enable-vnc.sh
      else
        curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
      fi


build_script:
  - sh: FOO=BAR

on_failure:
  - pwd
  
